export const consts = {
  titles: {
    edit: "ویرایش",
    delete: "حذف",
    show: "مشاهده",
    create: "ایجاد",
    cancel: "انصراف",
    toggleActivation: "تغییر وضعیت",
    revert: "بازگردانی",
    totalSelectedItem: "تعداد انتخاب شده ها",
    inActive: "غیرفعال",
    active: "فعال",
    yes: "بله",
    no: "خیر",
    dark: "تاریک",
    light: "روشن",
    system: "منطبق با سیستم",
    loginTitle: "شرکت سوده ایمن آرام",
    signIn: "ورود",
    forgotPassword: "فراموشی کلمه عبور",
    signUp: "ثبت نام",
    userName: "نام کاربری",
    password: "کلمه عبور",
    nationalCode: "کدملی",
    email: "ایمیل",
    phone: "همراه",
    forgotPasswordTitle: "بازیابی کلمه عبور",
    reset: "بازیابی",
    returnToLogin: "بازگشت به صفحه ورود",
    brandTitle: "شرکت سوده ایمن آرام",
    logout: "خروج",
    userCreate: "ایجاد کاربر",
    userEdit: "ویرایش کاربر",
  },
  questions: {
    delete: "آیا برای حذف موارد انتخابی موافق هستید؟",
    revert: "آیا برای بازگردانی موارد انتخابی موافق هستید؟",
  },
  placeholders: {
    enterUserName: "نام کاربری را وارد نمایید",
    enterPassword: "کلمه عبور را وارد نمایید",
    enterNationalCode: "کدملی خود را وارد نمایید",
    enterEmail: "ایمیل را وارد نمایید",
    enterPhone: "همراه را وارد نمایید",
  },
  errors: {
    requiredUserName: "نام کاربری اجباریست",
    requiredPassword: " کلمه عبور اجباریست",
    requirednationalCode: " کدملی اجباریست",
    requiredEmail: " ایمیل اجباریست",
    requiredPhone: " همراه اجباریست",
    regexUserName: "فقط از حروف و اعداد انگلیسی استفاده نمایید",
  },
  messages: {
    serverNotRunning:
      "سرور سرویس دهنده در حال حاضر در دسترس نیست. لطفا با پشتیبان نرم افزاری خود تماس حاصل نمایید",
    toggleMessage:
      "لطفا برای تغییر وضعیت موارد انتخابی یکی از گزینه ها را انتخاب نمایید",
  },
};
