export const Consts = {
  yourNationalCode: 'کدملی اجباریست',
  emailRequiredMessage: 'ایمیل اجباریست',
  phoneRequiredMessage: 'شماره همراه به درستی وارد نشده است',
  usernameRequiredMessage: 'نام کاربری اجباریست',
  passwordRequiredMessage: 'رمزعبور اجباریست',
  passwordIsNotStrongMessage: 'رمز قدرتمند نیست',
  minLengthOfPassword: 'حداقل طول رمز عبور برابر 2 است',
  UserIdIsRequired: 'شناسه کاربر اجباریست',
  yourRealEmail: 'ایمیل واقعی',
  yourRealPhone: 'شماره همراه',
  yourUserName: 'نام کاربری',
  yourPassword: 'رمزعبور',
  yourUserIdentifier: 'شناسه کاربر',
  createDate: 'تاریخ ایجاد',
  updateDate: 'تاریخ بروزرسانی',
  deleteDate: 'تاریخ حذف',
  revertDate: 'تاریخ برگشت از حذف موقت',
  Roles: 'سطوح دسترسی',
  isActive: 'وضعیت فعال بودن کاربر',
  isDeleted: 'وضعیت حذف بودن کاربر',
  ids: 'شناسه ها',
  items: 'لیست رکوردها',
  DataNotFound: 'داده ای برای نمایش یافت نشد',
  Count: 'تعداد انجام شده',
  totalCount: 'تعداد کل رکوردها',
  pageSize: 'تعداد در هر نمایش',
  pageNumber: 'شماره صفحه',
  loginParamsIsNotValid: 'مقادیر وارد شده معتبر نیستند',
  accessToken: 'توکن',
  refreshToken: 'توکن تازه سازی',
  Duplicated: 'تکراری',
  unAuthorized: 'مجوزی وجود ندارد',
  successfullyLogOut: 'با موفقیت از برنامه خارج شدید.',
  wrongIncomingParameters: 'پارامترهای ورودی قابل شناسایی نیست',
  LockDownUser:
    'کاربری شما به دلیل تکرار اشتباه در ورود اطلاعات برای مدت 3 دقیقه قفل شده است',
  ForbiddenMessage: 'مجوز دسترسی به این عملیات/داده را ندارید',
  badRequestMessage: 'پارامترهای ورودی دارای مشکل هستند.',
  notAcceptableMessage: 'فرمت داده های ورودی قابل قبول نیست',
  requestTimeoutMessage: 'درخواست منقضی شده است',
  conflictMessage: 'دارای تداخل',
  payloadTooLargeMessage: 'حجم درخواست زیاد است',
  unsupportedMediaTypeMessage: 'مقادیر سربرگ درخواست قابل شناسایی نیست',
  internalServerMessage: 'خطای داخلی سمت سرور',
  notImplementedException: 'برخی از پارامترهای اجباری ارسال نشده است',
  methodNotAllowedMessage: 'نوع ارسال درخواست اشتباه است',
  badGatewayMessage: 'ارتباط با درگاه سرویس برقرار نشده است',
  userNotExist: 'کاربری با این مشخصات یافت نشد',
  menuParent: 'نام والد',
  menuLink: 'آدرس صفحه',
  menuName: 'عنوان صفحه',
  menuParentId: 'شناسه والد صفحه',
  menuRoles: 'نقش های دارای دسترسی به این صفحه',
  menuSelfId: 'شناسه شخصی صفحه',
  menuChildren: 'زیرمجموعه های یک صفحه',
  menuPersianName: 'نام فارسی صفحه',
  menuDescription: 'توضیحات تکمیلی از کارکرد صفحه',
  tokenExpired: 'توکن منقضی شده است',
  avatarPath: 'مسیر ذخیره عکس کاربر',
  avatarImage: 'عکس کاربر',
  userId: 'شناسه کاربر',
  limitationDiskSpaceWarning:
    'فضای ذخیره سازی شما به حداقل کاهش یافته است. لطفا برای مدیریت و افزودن فضای بیشتر هرچه سریعتر اقدام فرمایید. در صورت نادیده گرفتن این هشدار اطلاعات تاریخچه اقدامات انجام شده در سیستم برای ماههای گذشته پاک خواهند شد.',
  freeDiskSpace: 'هشدار مدیریت فضای ذخیره سازی',
  youCanNotRemoveAdminUsers: 'شما نمیتوانید کاربر ادمین سیستم را حذف نمایید.',
  pageId: 'شناسه صفحه',
  permittedPage: 'صفحات مجاز برای کاربر',
  user: 'کاربر',
  checkWritable: 'بررسی قابل نوشتن یا فقط خواندنی بودن صفحه',
  fileUploding: 'آپلود عکس کاربر در سیستم',
  name: 'نام',
  family: 'نام خانوادگی',
  nationalCode: 'کد ملی',
  birthDate: 'تاریخ تولد',
  status: 'وضعیت',
};
