export const Consts = {
  firstNameRequiredMessage: 'نام اجباریست',
  lastNameRequiredMessage: 'نام خانوادگی اجباریست',
  emailRequiredMessage: 'ایمیل اجباریست',
  phoneRequiredMessage: 'شماره همراه اجباریست',
  usernameRequiredMessage: 'نام کاربری اجباریست',
  passwordRequiredMessage: 'رمزعبور اجباریست',
  passwordIsNotStrongMessage: 'رمز قدرتمند نیست',
  minLengthOfPassword: 'حداقل طول رمز عبور برابر 2 است',
  UserIdIsRequired: 'شناسه کاربر اجباریست',
  yourRealName: 'نام واقعی',
  yourRealFamily: 'فامیلی واقعی',
  yourRealEmail: 'ایمیل واقعی',
  yourRealPhone: 'شماره همراه',
  yourUserName: 'نام کاربری',
  yourPassword: 'رمزعبور',
  yourUserIdentifier: 'شناسه کاربر',
  createDate: 'تاریخ ایجاد',
  updateDate: 'تاریخ بروزرسانی',
  deleteDate: 'تاریخ حذف',
  revertDate: 'تاریخ برگشت از حذف موقت',
  rules: 'سطوح دسترسی',
  isActive: 'وضعیت فعال بودن کاربر',
  isDeleted: 'وضعیت حذف بودن کاربر',
  ids: 'شناسه ها',
  DataNotFound: 'داده ای برای نمایش یافت نشد',
  Count: 'تعداد انجام شده',
};
