enum EnumRules {
  Accountant
  Admin
  Base
  Guest
  Inspector
  Manager
  Security
  User
  Viewer
}

input PrismaQuery {
  cursor: cursor
  distinct: distinct
  orderBy: orderBy
  select: select
  skip: Int
  take: Int
  where: where
}

input PrismaSingleQuery {
  where: where
}

type Query {
  userQueries(queries: PrismaQuery): [Users!]!
  userQuery(query: PrismaSingleQuery): Users!
}

type Users {
  """تاریخ ایجاد"""
  createDate: String

  """تاریخ حذف"""
  deleteDate: String

  """ایمیل واقعی"""
  email: String

  """نام واقعی"""
  firstName: String

  """شناسه کاربر"""
  id: String

  """وضعیت فعال بودن کاربر"""
  isActive: Boolean

  """فامیلی واقعی"""
  lastName: String

  """رمزعبور"""
  password: String

  """شماره همراه"""
  phone: String

  """سطوح دسترسی"""
  rules: [EnumRules!]

  """تاریخ بروزرسانی"""
  updateDate: String

  """نام کاربری"""
  userName: String
}

scalar cursor

scalar distinct

scalar orderBy

scalar select

scalar where